= Hunt the Wumpus

Terminal text-based game, made in Prolog, in which the goal is to collect gold and escape without getting caught by the Wumpus who lives there.

== Dependencies

You will need link:https://www.swi-prolog.org[SWI Prolog] to run this project.

== How to use it

[source,bash]
----
git clone https://github.com/dflat2/wumpus-prolog.git
cd wumpus-prolog
swipl wumpus.pl
start.
----

== What is _Hunt the Wumpus_?

Quoting link:https://en.wikipedia.org/wiki/Hunt_the_Wumpus[Wikipedia]:

[quote]
____
Hunt the Wumpus is a text-based adventure game developed by Gregory Yob in 1973. In the game, the player moves through a series of connected caves, arranged as the vertices of a dodecahedron, as they hunt a monster named the Wumpus. The turn-based game has the player trying to avoid fatal bottomless pits and "super bats" that will move them around the cave system; the goal is to fire one of their "crooked arrows" through the caves to kill the Wumpus. Yob created the game in early 1973 due to his annoyance at the multiple hide-and-seek games set in caves in a grid pattern, and it and multiple variations were sold via mail order by Yob and the People's Computer Company. The source code to the game was published in Creative Computing in 1975 and republished in The Best of Creative Computing the following year.
____

I discovered this game while reading link:http://aima.cs.berkeley.edu/[Artificial Intelligence: A Modern Approach].

